blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooCodeInc/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for ANH CHAT
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.anh-cline&ssr=false#review-details
      about: Enjoying ANH CHAT? Leave a review here!
